#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Task5R Phase 5 — label-free identity separability gate (R0-R6).

For every near-contact leaf pair in benchmark_manifest.json:
  * build kNN candidate edges among the union of the TWO proposed leaf
    components ONLY (candidate selection uses geometry alone, never the
    labels being tested — labels enter only POST-HOC to name an edge
    within/cross);
  * compute G6/G7 identity features from the CORRECTED occlusion-aware
    real-observation signature (core.observation_identity);
  * score each edge under frozen ablations:
      R0  euclidean distance control (expect NO separation)
      R1  c_vis   (visibility Jaccard)
      R2  c_app   (appearance cosine, real RGB)
      R3  c_occ   (occlusion/depth-order consistency)
      R4  c_mv    (0.4 c_vis + 0.3 c_app + 0.3 c_occ)
      R5  surface coherence (local-PCA normal alignment) only
      R6  c_mv AND surface coherence combined score
  * within-edge := both endpoints in the SAME proposed leaf; cross-edge :=
    endpoints in DIFFERENT leaves of the pair; stem/background edges are not
    generated by construction (components exclude stem-like points).

Metrics per pair and aggregated: counts, median/IQR within vs cross, AUROC
(within = positive class), AUPRC + prevalence + lift, bootstrap 95% CI,
Cliff's delta effect size, dev vs held-out split reported separately.
Dev plants may choose thresholds; held-out is evaluated ONCE, frozen.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from pathlib import Path

import numpy as np

_SCRIPT = Path(__file__).resolve()
REPO_DEFAULT = _SCRIPT.parent.parent
for p in (str(REPO_DEFAULT), str(REPO_DEFAULT / "core")):
    if p not in sys.path:
        sys.path.insert(0, p)

from core.observation_identity import git_commit  # noqa: E402
from core.geodesic_backends import _mv_edge_features  # noqa: E402


def load_viewsig(cache_dir: Path, plant: str):
    files = sorted((cache_dir / plant).glob("corrected_viewsig_*.npz"))
    if not files:
        raise FileNotFoundError(f"no corrected viewsig for {plant}")
    return np.load(files[-1])


def local_pca_normals(xyz, k=16):
    from scipy.spatial import cKDTree
    tree = cKDTree(xyz)
    _, idx = tree.query(xyz, k=k + 1)
    N = len(xyz)
    nrm = np.empty((N, 3), dtype=np.float64)
    CH = 200000
    for s in range(0, N, CH):
        nb = xyz[idx[s:s+CH, 1:k+1]]
        nbc = nb - nb.mean(axis=1, keepdims=True)
        cov = np.einsum("nki,nkj->nij", nbc, nbc)
        w, V = np.linalg.eigh(cov)
        nrm[s:s+CH] = V[:, :, 0]
    return nrm


def surface_coherence(nrm, rows, cols):
    seg = xyz_seg(rows, cols)
    dn = np.abs(np.einsum("nc,nc->n", nrm[rows], seg))
    return dn / (np.linalg.norm(seg, axis=1) + 1e-12)


_XYZ = None


def xyz_seg(rows, cols):
    return _XYZ[cols] - _XYZ[rows]


def auroc(scores, labels):
    """AUROC with within-leaf as positive class. Rank-based (handles ties)."""
    s = np.asarray(scores, dtype=np.float64)
    y = np.asarray(labels, dtype=bool)
    n_pos, n_neg = int(y.sum()), int((~y).sum())
    if n_pos == 0 or n_neg == 0:
        return None
    order = np.argsort(s)
    ranks = np.empty(len(s), dtype=np.float64)
    ranks[order] = np.arange(1, len(s) + 1)
    # midranks for ties
    s_sorted = s[order]
    i = 0
    while i < len(s_sorted):
        j = i
        while j + 1 < len(s_sorted) and s_sorted[j + 1] == s_sorted[i]:
            j += 1
        if j > i:
            ranks[order[i:j+1]] = (i + j) / 2.0 + 1.0
        i = j + 1
    return float((ranks[y].sum() - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg))


def auprc(scores, labels):
    """Average precision with within-leaf as positive class."""
    s = np.asarray(scores, dtype=np.float64)
    y = np.asarray(labels, dtype=bool)
    n_pos = int(y.sum())
    if n_pos == 0:
        return None
    order = np.argsort(-s)
    y_sorted = y[order]
    tp = np.cumsum(y_sorted)
    prec = tp / np.arange(1, len(y) + 1)
    return float((prec * y_sorted).sum() / n_pos)


def cliffs_delta(a, b):
    """Nonparametric effect size P(a>b) - P(a<b)."""
    a = np.asarray(a); b = np.asarray(b)
    if len(a) == 0 or len(b) == 0:
        return None
    gt = lt = 0.0
    bs = len(b)
    for x in a[:4000]:  # cap for tractability
        gt += float((x > b).sum())
        lt += float((x < b).sum())
    return float((gt - lt) / (min(len(a), 4000) * bs))


def bootstrap_ci(scores, labels, stat=auroc, n_boot=1000, seed=0, ci=(2.5, 97.5)):
    rng = np.random.default_rng(seed)
    vals = []
    y = np.asarray(labels, dtype=bool)
    idx_pos = np.where(y)[0]
    idx_neg = np.where(~y)[0]
    for _ in range(n_boot):
        take = np.concatenate([rng.choice(idx_pos, len(idx_pos), replace=True),
                               rng.choice(idx_neg, len(idx_neg), replace=True)])
        v = stat(scores[take], y[take])
        if v is not None:
            vals.append(v)
    if not vals:
        return None
    return [float(np.percentile(vals, ci[0])), float(np.percentile(vals, ci[1]))]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=None)
    ap.add_argument("--dense-root", default=None)
    ap.add_argument("--manifest", default=None)
    ap.add_argument("--cache-dir", default=None)
    ap.add_argument("--output-csv", default=None)
    ap.add_argument("--output-summary", default=None)
    ap.add_argument("--knn", type=int, default=32,
                    help="candidate edges: kNN within the two-leaf point union")
    ap.add_argument("--n-boot", type=int, default=1000)
    ap.add_argument("--seed", type=int, default=0)
    ar = ap.parse_args()

    repo_root = Path(ar.repo_root).resolve() if ar.repo_root else REPO_DEFAULT
    dense_root = Path(ar.dense_root).resolve() if ar.dense_root else \
        repo_root.parent / "datasets" / "07-SuGaR-GS"
    cache_dir = Path(ar.cache_dir).resolve() if ar.cache_dir else \
        repo_root / "outputs" / "task5r" / "projection_cache"
    manifest_path = Path(ar.manifest) if ar.manifest else \
        repo_root / "outputs" / "task5r" / "benchmark_manifest.json"

    global _XYZ
    sys.path[:0] = [str(repo_root), str(repo_root / "core")]
    from core.real_observation import load_dense_gaussian_plant

    man = json.loads(manifest_path.read_text())
    rows_out = []

    plant_cache = {}
    for plant, cases in sorted(man["cases"].items()):
        g = load_dense_gaussian_plant(str(dense_root / plant))
        z = load_viewsig(cache_dir, plant)
        visible = z["visible"]                    # (V,N) bool
        max_alpha = z["max_alpha"]
        rgb_valid = z["rgb_valid"]
        w_rgbv = max_alpha * rgb_valid
        num_c = np.einsum("vnc,vn->nc", z["rgb_views"].astype(np.float64),
                          w_rgbv.astype(np.float64))
        den_c = w_rgbv.sum(axis=0)
        col = np.full((len(g), 3), np.nan)
        okc = den_c > 0
        col[okc] = num_c[okc] / den_c[okc, None]
        # appear_sig must be finite where used; NaN->0 vector keeps cosine 0
        appear = np.nan_to_num(col, nan=0.0).astype(np.float32)
        depth = np.nan_to_num(z["depth"], posinf=0.0).astype(np.float32)
        uv = z["uv_ndc"].astype(np.float32)
        uv = np.nan_to_num(uv, nan=0.0)
        _XYZ = np.asarray(g.xyz, dtype=np.float64)
        nrm = local_pca_normals(_XYZ)

        # proposed leaf masks from the FROZEN independent proposer params
        from scripts.audit_real_overlap_cases import propose_leaf_labels_independent
        vf = z["visibility_fraction"]
        lab, _ = propose_leaf_labels_independent(g, vf, col=col)

        for case in cases:
            ia, ib = case["a"], case["b"]
            ids_a = np.where(lab == ia)[0]
            ids_b = np.where(lab == ib)[0]
            sel = np.concatenate([ids_a, ids_b])
            pos = {int(p): i for i, p in enumerate(sel)}
            # kNN candidate edges WITHIN the two-leaf union (geometry only)
            from scipy.spatial import cKDTree
            from scipy.sparse import coo_matrix
            P = _XYZ[sel]
            tree = cKDTree(P)
            dists, nbrs = tree.query(P, k=min(ar.knn + 1, len(sel)))
            er = np.repeat(np.arange(len(sel)), nbrs.shape[1] - 1)
            ec = nbrs[:, 1:].ravel()
            ed = dists[:, 1:].ravel()
            # undirected dedup
            lo = np.minimum(er, ec); hi = np.maximum(er, ec)
            key = lo.astype(np.int64) * len(sel) + hi
            uniq = np.unique(key)
            ulo, uhi = uniq // len(sel), uniq % len(sel)
            r_abs = sel[ulo]; c_abs = sel[uhi]

            is_within = (lab[r_abs] == lab[c_abs])
            vis_sub = visible[:, r_abs], visible[:, c_abs]
            c_vis, c_app, c_occ = _mv_edge_features(
                r_abs, c_abs, visible, appear, depth, uv, visible.shape[0])
            sin_sc = surface_coherence(nrm, r_abs, c_abs)
            c_mv = 0.4 * c_vis + 0.3 * c_app + 0.3 * c_occ
            sc01 = np.clip(1.0 - sin_sc, 0.0, 1.0)
            # distance control (negated so larger = more likely within)
            d_edge = np.linalg.norm(_XYZ[c_abs] - _XYZ[r_abs], axis=1)
            ablations = {
                "R0_dist": -d_edge,          # larger = more likely within
                "R1_c_vis": c_vis,
                "R2_c_app": c_app,
                "R3_c_occ": c_occ,
                "R4_c_mv": c_mv,
                "R5_surface": sc01,
                "R6_mv_and_surface": np.minimum(c_mv, sc01),
            }
            for name, sc in ablations.items():
                au = auroc(sc, is_within)
                pr = auprc(sc, is_within)
                prev = float(is_within.mean())
                sw = sc[is_within]; sx = sc[~is_within]
                cd = cliffs_delta(sw, sx)
                bci = bootstrap_ci(sc, is_within, n_boot=ar.n_boot, seed=ar.seed)
                rows_out.append({
                    "plant": plant, "case_id": case["case_id"],
                    "ablation": name, "n_edges": int(len(is_within)),
                    "n_within": int(is_within.sum()), "n_cross": int((~is_within).sum()),
                    "prevalence": round(prev, 4),
                    "median_within": float(np.median(sw)) if len(sw) else None,
                    "q25_within": float(np.percentile(sw, 25)) if len(sw) else None,
                    "q75_within": float(np.percentile(sw, 75)) if len(sw) else None,
                    "median_cross": float(np.median(sx)) if len(sx) else None,
                    "q25_cross": float(np.percentile(sx, 25)) if len(sx) else None,
                    "q75_cross": float(np.percentile(sx, 75)) if len(sx) else None,
                    "auroc": au, "auprc": pr, "auprc_lift_over_prevalence":
                        (pr / prev) if pr is not None else None,
                    "cliffs_delta": cd,
                    "auroc_ci95_lo": bci[0] if bci else None,
                    "auroc_ci95_hi": bci[1] if bci else None,
                })
            print(f"[{case['case_id']}] edges={len(is_within)} "
                  f"within={int(is_within.sum())} cross={int((~is_within).sum())} "
                  f"AUROC mv={rows_out[-4]['auroc']:.3f}", flush=True)

    out_csv = Path(ar.output_csv) if ar.output_csv else \
        repo_root / "outputs" / "task5r" / "edge_separability.csv"
    with open(out_csv, "w", newline="") as f:
        wcsv = csv.DictWriter(f, fieldnames=list(rows_out[0].keys()))
        wcsv.writeheader()
        wcsv.writerows(rows_out)

    # aggregate summary per ablation x split
    def agg(rs):
        aus = [r["auroc"] for r in rs if r["auroc"] is not None]
        prs = [r["auprc"] for r in rs if r["auprc"] is not None]
        cds = [r["cliffs_delta"] for r in rs if r["cliffs_delta"] is not None]
        return {"n_pairs": len({r["case_id"] for r in rs}),
                "mean_auroc": float(np.mean(aus)) if aus else None,
                "min_auroc": float(np.min(aus)) if aus else None,
                "mean_auprc": float(np.mean(prs)) if prs else None,
                "mean_prevalence": float(np.mean([r["prevalence"] for r in rs])),
                "mean_cliffs_delta": float(np.mean(cds)) if cds else None}

    summary = {
        "task": "Task5R Phase5 identity separability gate",
        "git_commit": git_commit(repo_root),
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "protocol": {
            "candidates": f"{ar.knn}-NN within two-leaf union, geometry only",
            "positive_class": "within-leaf",
            "features_source": "corrected occlusion-aware real viewsig "
                               "(core.observation_identity)",
            "bootstrap": ar.n_boot, "seed": ar.seed,
            "dev_plants": man["dev_plants"],
            "heldout_plants": man["heldout_plants"],
        },
        "by_split_ablation": {},
    }
    devp = set(man["dev_plants"]); hdp = set(man["heldout_plants"])
    for split, psel in (("dev", devp), ("heldout", hdp)):
        sub = [r for r in rows_out if r["plant"] in psel]
        byab = {}
        for r in sub:
            byab.setdefault(r["ablation"], []).append(r)
        for ab, rs in sorted(byab.items()):
            summary["by_split_ablation"].setdefault(split, {})[ab] = agg(rs)

    out_sum = Path(ar.output_summary) if ar.output_summary else \
        repo_root / "outputs" / "task5r" / "edge_separability_summary.json"
    out_sum.write_text(json.dumps(summary, indent=2))
    print("WROTE", out_csv)
    print("WROTE", out_sum)
    return 0


if __name__ == "__main__":
    sys.exit(main())
